-- MySQL Script generated by MySQL Workbench
-- Wed Apr 16 08:53:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ubicaciones` (
  `id_ubicaciones` INT NOT NULL,
  `ciudad` VARCHAR(70) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_ubicaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aeropuertos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aeropuertos` (
  `id_aeropuertos` INT NOT NULL,
  ` nombre` VARCHAR(100) NOT NULL,
  `codigo_iata` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_ubicaciones` INT NOT NULL,
  PRIMARY KEY (`id_aeropuertos`, `id_ubicaciones`),
  INDEX `fk_aeropuertos_ubicaciones1_idx` (`id_ubicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_aeropuertos_ubicaciones1`
    FOREIGN KEY (`id_ubicaciones`)
    REFERENCES `mydb`.`ubicaciones` (`id_ubicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vuelo` (
  `id_Vuelos` INT NOT NULL,
  `numero_vuelo` VARCHAR(45) NOT NULL,
  `aerolinea` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_origen` INT NOT NULL,
  `id_destino` INT NOT NULL,
  PRIMARY KEY (`id_Vuelos`, `id_origen`, `id_destino`),
  INDEX `fk_Vuelo_aeropuertos1_idx` (`id_origen` ASC) VISIBLE,
  INDEX `fk_Vuelo_aeropuertos2_idx` (`id_destino` ASC) VISIBLE,
  CONSTRAINT `fk_Vuelo_aeropuertos1`
    FOREIGN KEY (`id_origen`)
    REFERENCES `mydb`.`aeropuertos` (`id_aeropuertos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vuelo_aeropuertos2`
    FOREIGN KEY (`id_destino`)
    REFERENCES `mydb`.`aeropuertos` (`id_ubicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vuelos_programados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vuelos_programados` (
  `ID_vuelo_programado` INT NOT NULL,
  `id_vuelo` INT NOT NULL,
  `fecha_hora_salida` DATETIME NOT NULL,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`ID_vuelo_programado`, `id_vuelo`),
  INDEX `fk_vuelos_programados_Vuelo_idx` (`id_vuelo` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_programados_Vuelo`
    FOREIGN KEY (`id_vuelo`)
    REFERENCES `mydb`.`Vuelo` (`id_Vuelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escalas` (
  `id_escala` INT NOT NULL,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `fecha_hora_salida` DATETIME NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuarios` INT NULL,
  `id_aeropuerto` INT NOT NULL,
  `id_vuelo_programado` INT NOT NULL,
  PRIMARY KEY (`id_escala`, `id_aeropuerto`, `id_vuelo_programado`),
  INDEX `fk_escalas_aeropuertos1_idx` (`id_aeropuerto` ASC) VISIBLE,
  INDEX `fk_escalas_vuelos_programados1_idx` (`id_vuelo_programado` ASC) VISIBLE,
  CONSTRAINT `fk_escalas_aeropuertos1`
    FOREIGN KEY (`id_aeropuerto`)
    REFERENCES `mydb`.`aeropuertos` (`id_aeropuertos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escalas_vuelos_programados1`
    FOREIGN KEY (`id_vuelo_programado`)
    REFERENCES `mydb`.`vuelos_programados` (`ID_vuelo_programado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_reserva` (
  `id_estado_reserva` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_estado_reserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL,
  `nombre_tipo` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id_usuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`, `id_tipo_usuario`),
  INDEX `fk_Usuarios_tipo_usuario1_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `mydb`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `id_reserva` INT NOT NULL,
  `fecha_hora_reserva` DATETIME NOT NULL,
  `cantidad_pasajeros` INT NOT NULL,
  `costo_total` INT NOT NULL,
  `ID_estado_reserva` INT NOT NULL,
  `Id_usuarios` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_reserva`, `ID_estado_reserva`, `Id_usuarios`),
  INDEX `fk_reservas_estado_reserva1_idx` (`ID_estado_reserva` ASC) VISIBLE,
  INDEX `fk_reservas_Usuarios1_idx` (`Id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_estado_reserva1`
    FOREIGN KEY (`ID_estado_reserva`)
    REFERENCES `mydb`.`estado_reserva` (`id_estado_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_Usuarios1`
    FOREIGN KEY (`Id_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` reservas_vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` reservas_vuelos` (
  `id_reserva_vuelo` INT NOT NULL,
  `id_reserva` INT NOT NULL,
  `id_vuelos_programado` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuarios` INT NULL,
  PRIMARY KEY (`id_reserva_vuelo`, `id_reserva`, `id_vuelos_programado`),
  INDEX `fk_ reservas_vuelos_reservas1_idx` (`id_reserva` ASC) VISIBLE,
  INDEX `fk_ reservas_vuelos_vuelos_programados1_idx` (`id_vuelos_programado` ASC) VISIBLE,
  CONSTRAINT `fk_ reservas_vuelos_reservas1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `mydb`.`reservas` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ reservas_vuelos_vuelos_programados1`
    FOREIGN KEY (`id_vuelos_programado`)
    REFERENCES `mydb`.`vuelos_programados` (`ID_vuelo_programado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_asiento` (
  `id_estado_asiento` INT NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_estado_asiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clase_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clase_asiento` (
  `id_clase_asiento` INT NOT NULL,
  `tipo_clase` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_clase_asiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asientos` (
  `id_asientos` INT NOT NULL,
  `numero_asiento` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_reserva` INT NOT NULL,
  `id_estado_asiento` INT NOT NULL,
  `id_clase_asiento` INT NOT NULL,
  PRIMARY KEY (`id_asientos`, `id_reserva`, `id_estado_asiento`, `id_clase_asiento`),
  INDEX `fk_asientos_reservas1_idx` (`id_reserva` ASC) VISIBLE,
  INDEX `fk_asientos_estado_asiento1_idx` (`id_estado_asiento` ASC) VISIBLE,
  INDEX `fk_asientos_clase_asiento1_idx` (`id_clase_asiento` ASC) VISIBLE,
  CONSTRAINT `fk_asientos_reservas1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `mydb`.`reservas` (`Id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_estado_asiento1`
    FOREIGN KEY (`id_estado_asiento`)
    REFERENCES `mydb`.`estado_asiento` (`id_estado_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_clase_asiento1`
    FOREIGN KEY (`id_clase_asiento`)
    REFERENCES `mydb`.`clase_asiento` (`id_clase_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
